name: Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  delete-neon-branch:
    name: Delete Neon Branch
    runs-on: ubuntu-latest
    steps:
      - uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: ci/pr-${{ github.event.pull_request.number }}
          api_key: ${{ secrets.NEON_API_KEY }}
